/*
 * Travel mircro service
 * Micro service to book a escaperoom
 *
 * OpenAPI spec version: 1.0.0
 * Contact: supportm@bp.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.bp.escaperoom.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * RoomService
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-06T08:44:40.322365400+01:00[Europe/Warsaw]")
public class RoomService {
  @JsonProperty("typeOfService") //rodzaj usługi (picie czy jedzenie)
  private String typeOfService = null;

  @JsonProperty("levelOfService") //poziom usługi
  private Integer levelOfService = null;

  public RoomService from(String from) {
    this.typeOfService = from;
    return this;
  }

   /**
   * Get from
   * @return from
  **/

  public String getTypeOfService() {
    return typeOfService;
  }

  public void setTypeOfService(String typeOfService) {
    this.typeOfService = typeOfService;
  }

  public RoomService to(Integer to) {
    this.levelOfService = to;
    return this;
  }

   /**
   * Get to
   * @return to
  **/

  public Integer getLevelOfService() {
    return levelOfService;
  }

  public void setLevelOfService(Integer levelOfService) {
    this.levelOfService = levelOfService;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RoomService roomService = (RoomService) o;
    return Objects.equals(this.typeOfService, roomService.typeOfService) &&
        Objects.equals(this.levelOfService, roomService.levelOfService);
  }

  @Override
  public int hashCode() {
    return Objects.hash(typeOfService, levelOfService);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RoomService {\n");
    
    sb.append("    from: ").append(toIndentedString(typeOfService)).append("\n");
    sb.append("    to: ").append(toIndentedString(levelOfService)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
