/*
 * Travel mircro service
 * Micro service to book a escaperoom
 *
 * OpenAPI spec version: 1.0.0
 * Contact: supportm@bp.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.bp.escaperoom.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.time.OffsetDateTime;
/**
 * Room
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-06T08:44:40.322365400+01:00[Europe/Warsaw]")
public class Room {
  @JsonProperty("name") //nazwa
  private String name = null;

  @JsonProperty("city") //miasto
  private String city = null;

  @JsonProperty("difficulty") //trudnosc
  private String difficulty = null;

//  @JsonProperty("address")
//  private String address = null;

  @JsonProperty("checkIn") //godzina
  private OffsetDateTime startTime = null;

//  @JsonProperty("checkOut")
//  private OffsetDateTime checkOut = null;

  public Room name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Room city(String city) {
    this.city = city;
    return this;
  }

   /**
   * Get city
   * @return city
  **/

  public String getCity() {
    return city;
  }

  public void setCity(String city) {
    this.city = city;
  }

  public Room country(String country) {
    this.difficulty = country;
    return this;
  }

   /**
   * Get country
   * @return country
  **/

  public String getDifficulty() {
    return difficulty;
  }

  public void setDifficulty(String difficulty) {
    this.difficulty = difficulty;
  }

//  public Room address(String address) {
//    this.address = address;
//    return this;
//  }

   /**
   * Get address
   * @return address
  **/

//  public String getAddress() {
//    return address;
//  }
//
//  public void setAddress(String address) {
//    this.address = address;
//  }

  public Room checkIn(OffsetDateTime checkIn) {
    this.startTime = checkIn;
    return this;
  }

   /**
   * Get checkIn
   * @return checkIn
  **/

  public OffsetDateTime getStartTime() {
    return startTime;
  }

  public void setStartTime(OffsetDateTime startTime) {
    this.startTime = startTime;
  }

//  public Room checkOut(OffsetDateTime checkOut) {
//    this.checkOut = checkOut;
//    return this;
//  }

   /**
   * Get checkOut
   * @return checkOut
  **/

//  public OffsetDateTime getCheckOut() {
//    return checkOut;
//  }
//
//  public void setCheckOut(OffsetDateTime checkOut) {
//    this.checkOut = checkOut;
//  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Room room = (Room) o;
    return Objects.equals(this.name, room.name) &&
        Objects.equals(this.city, room.city) &&
        Objects.equals(this.difficulty, room.difficulty) &&
//        Objects.equals(this.address, room.address) &&
        Objects.equals(this.startTime, room.startTime);
//        Objects.equals(this.checkOut, room.checkOut);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, city, difficulty, startTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Room {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    country: ").append(toIndentedString(difficulty)).append("\n");
//    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    checkIn: ").append(toIndentedString(startTime)).append("\n");
//    sb.append("    checkOut: ").append(toIndentedString(checkOut)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
